"""
DevOps Sentinel - Data Models
=============================
Pydantic models for type-safe data handling.
"""

from datetime import datetime
from enum import Enum
from typing import Optional, List
from pydantic import BaseModel, Field, HttpUrl
from uuid import UUID, uuid4


# ===== Enums =====

class ServiceStatus(str, Enum):
    """Current status of a monitored service."""
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    DOWN = "down"
    UNKNOWN = "unknown"


class IncidentStatus(str, Enum):
    """Incident lifecycle states."""
    DETECTING = "detecting"
    ALERTING = "alerting"
    INVESTIGATING = "investigating"
    RESOLVED = "resolved"


class IncidentSeverity(str, Enum):
    """Incident severity levels."""
    CRITICAL = "critical"
    HIGH = "high"
    MEDIUM = "medium"
    LOW = "low"


# ===== Service Models =====

class ServiceConfig(BaseModel):
    """Configuration for a monitored service."""
    id: UUID = Field(default_factory=uuid4)
    name: str = Field(..., min_length=1, max_length=100)
    url: str = Field(..., description="URL to monitor")
    check_interval: int = Field(default=10, ge=1, description="Check interval in seconds")
    is_active: bool = Field(default=True)
    created_at: datetime = Field(default_factory=datetime.utcnow)
    
    class Config:
        json_schema_extra = {
            "example": {
                "name": "Payment API",
                "url": "https://api.example.com/health",
                "check_interval": 10
            }
        }


class HealthCheckResult(BaseModel):
    """Result of a single health check."""
    service_id: UUID
    status_code: Optional[int] = None
    response_time_ms: float
    is_healthy: bool
    error_message: Optional[str] = None
    response_body: Optional[str] = None
    checked_at: datetime = Field(default_factory=datetime.utcnow)


# ===== Incident Models =====

class TimelineEvent(BaseModel):
    """A single event in an incident timeline."""
    timestamp: datetime = Field(default_factory=datetime.utcnow)
    event_type: str
    description: str
    agent: Optional[str] = None
    data: Optional[dict] = None


class Incident(BaseModel):
    """Full incident record with timeline."""
    id: UUID = Field(default_factory=uuid4)
    service_id: UUID
    service_name: str
    service_url: str
    status: IncidentStatus = Field(default=IncidentStatus.DETECTING)
    severity: IncidentSeverity = Field(default=IncidentSeverity.MEDIUM)
    
    # Timing
    detected_at: datetime = Field(default_factory=datetime.utcnow)
    alerted_at: Optional[datetime] = None
    resolved_at: Optional[datetime] = None
    mttd_seconds: Optional[float] = None
    mttr_seconds: Optional[float] = None
    
    # Error details
    error_code: Optional[int] = None
    error_message: Optional[str] = None
    
    # Agent outputs
    triage_summary: Optional[str] = None
    investigation_report: Optional[str] = None
    action_plan: Optional[str] = None
    
    # Timeline
    timeline: List[TimelineEvent] = Field(default_factory=list)
    
    def add_event(self, event_type: str, description: str, agent: str = None, data: dict = None):
        """Add an event to the incident timeline."""
        self.timeline.append(TimelineEvent(
            event_type=event_type,
            description=description,
            agent=agent,
            data=data
        ))


class Postmortem(BaseModel):
    """AI-generated incident postmortem."""
    id: UUID = Field(default_factory=uuid4)
    incident_id: UUID
    
    # Content
    title: str
    summary: str
    timeline_markdown: str
    root_cause_analysis: str
    action_items: List[str] = Field(default_factory=list)
    lessons_learned: Optional[str] = None
    
    # Metadata
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    generated_by_model: str
    
    def to_markdown(self) -> str:
        """Convert postmortem to markdown format."""
        action_items_md = "\n".join(f"- [ ] {item}" for item in self.action_items)
        return f"""# {self.title}

## Summary
{self.summary}

## Timeline
{self.timeline_markdown}

## Root Cause Analysis
{self.root_cause_analysis}

## Action Items
{action_items_md}

## Lessons Learned
{self.lessons_learned or "N/A"}

---
*Generated by DevOps Sentinel using {self.generated_by_model}*
"""


# ===== Agent Response Models =====

class AgentResponse(BaseModel):
    """Standardized response from an agent."""
    agent_name: str
    task_name: str
    output: str
    execution_time_seconds: float
    tokens_used: Optional[int] = None
    model_used: str


# ===== Lint Result Models =====

class LintIssue(BaseModel):
    """A single linting issue."""
    file: str
    line: int
    column: int
    code: str
    message: str
    severity: str  # error, warning, info


class LintResult(BaseModel):
    """Result of a pre-deploy lint check."""
    passed: bool
    total_issues: int
    issues: List[LintIssue] = Field(default_factory=list)
    checked_at: datetime = Field(default_factory=datetime.utcnow)
