import SiteTopNav from '../components/site/SiteTopNav'
import SiteFooter from '../components/site/SiteFooter'
import './Legal.css'

const NAV_LINKS = [
  { to: '/terms', label: 'Terms' },
  { to: '/docs', label: 'Docs' },
]

const FOOTER_LINKS = [
  { to: '/about', label: 'About' },
  { to: '/terms', label: 'Terms' },
  { to: '/docs', label: 'Docs' },
]

export default function Privacy() {
  return (
    <div className="site-page legal-page">
      <a className="site-skip-link" href="#legal-main">Skip to content</a>

      <SiteTopNav links={NAV_LINKS} />

      <main id="legal-main" className="site-main site-container legal-main">
        <article className="site-card legal-content-card">
          <p className="site-label">Privacy Policy</p>
          <h1 className="site-title">Privacy Policy</h1>
          <p className="legal-last-updated">Last updated: January 28, 2026</p>

          <section>
            <h2>Information we collect</h2>
            <ul>
              <li>Account details such as name and email</li>
              <li>Service URLs and monitoring configuration</li>
              <li>Incident and operational metadata generated by product usage</li>
            </ul>
          </section>

          <section>
            <h2>How information is used</h2>
            <ul>
              <li>Operate monitoring and incident features</li>
              <li>Send service alerts and operational notifications</li>
              <li>Improve reliability and product quality</li>
            </ul>
          </section>

          <section>
            <h2>Information sharing</h2>
            <p>
              We do not sell personal data. We may share necessary data with infrastructure or
              service providers that support product operations, and where legally required.
            </p>
          </section>

          <section>
            <h2>Data security</h2>
            <p>
              We apply standard safeguards including encrypted transport, access controls, and
              operational monitoring.
            </p>
          </section>

          <section>
            <h2>Your rights</h2>
            <ul>
              <li>Request access to your data</li>
              <li>Request deletion where applicable</li>
              <li>Request export of account-related data</li>
            </ul>
          </section>

          <section>
            <h2>Contact</h2>
            <p>
              Privacy questions: <a href="mailto:privacy@devops-sentinel.dev">privacy@devops-sentinel.dev</a>
            </p>
          </section>
        </article>
      </main>

      <SiteFooter links={FOOTER_LINKS} text="DevOps Sentinel legal" />
    </div>
  )
}
